<?php

/**

 * Genesis Framework.

 *

 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.

 * Please do all modifications in the form of a child theme.

 *

 * @package Genesis\Templates

 * @author  StudioPress

 * @license GPL-2.0+

 * @link    http://my.studiopress.com/themes/genesis/

 */



do_action( 'genesis_doctype' );

do_action( 'genesis_title' );

do_action( 'genesis_meta' );



wp_head(); //* we need this for plugins

?>

<script type="text/javascript">var switchTo5x=true;</script>

<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>

<script type="text/javascript">stLight.options({publisher: "96d0ad19-e4c2-42dd-865b-461d0770128f",  onhover: false, doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

</head>

<?php

genesis_markup( array(

  'html5'   => '<body %s>',

  'xhtml'   => sprintf( '<body class="%s">', implode( ' ', get_body_class() ) ),

  'context' => 'body',

) );

do_action( 'genesis_before' );



genesis_markup( array(

  'html5'   => '<div %s>',

  'xhtml'   => '<div id="wrap">',

  'context' => 'site-container',

) );



do_action( 'genesis_before_header' );

do_action( 'genesis_header' );

do_action( 'genesis_after_header' );



genesis_markup( array(

  'html5'   => '<div %s>',

  'xhtml'   => '<div id="inner">',

  'context' => 'site-inner',

) );

genesis_structural_wrap( 'site-inner' );

?>

<div class="wrap" style="position: absolute;top: -102px;z-index: 999;right:0;width: 60%;">

<div class="row header-banner">

<div class="column one-thirds">

       <!--  <img src="/wp-content/uploads/2014/10/kore-logo.png" alt="KoreConX Logo"> -->

    </div>

<div class="column two-thirds"  style="width: 100%;">

<h2 class="featured-tagline">Eco-System Infrastructure Platform (ESIP)<span style="color:#fff;">making the pieces fit</span></h2>

<p></p></div>

</div></div>
<br><br>


<!-- Start of Async HubSpot Analytics Code -->

  <script type="text/javascript">

    (function(d,s,i,r) {

      if (d.getElementById(i)){return;}

      var n=d.createElement(s),e=d.getElementsByTagName(s)[0];

      n.id=i;n.src='//js.hs-analytics.net/analytics/'+(Math.ceil(new Date()/r)*r)+'/455112.js';

      e.parentNode.insertBefore(n, e);

    })(document,"script","hs-analytics",300000);

  </script>

<!-- End of Async HubSpot Analytics Code -->